# arithmetic progression(AP)
[arithmetic progression(AP)](https://he.wikipedia.org/wiki/%D7%A1%D7%93%D7%A8%D7%94_%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%99%D7%AA)

Lastly, I want to mention two very useful functions for creating sequences of numbers within a specified range, namely, arange and linspace. NumPy’s arange function follows the same syntax as Python’s range objects: If two arguments are provided, the first argument represents the start value and the second value defines the stop value of a half-open interval:

Numpy also has two useful functions for creating sequences of numbers: `arange` and `linspace`.

The [`arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) function accepts three arguments, which define the start value, stop value of a half-open interval, and step size. (The default step size, if not explicitly specified, is 1; the default start value, if not explicitly specified, is 0.)

The [`linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) function is similar, but we can specify the number of values instead of the step size, and it will create a sequence of evenly spaced values.

In [ ]:
import numpy as np

In [ ]:
c = np.arange(10)   # Create an array of values starting at 0 in increments of 1
print(c)

[0 1 2 3 4 5 6 7 8 9]


Note this ends on 9, not 10 (does not include the top end of the interval).

In [ ]:
c = np.arange(2,8)   # Create an array of values starting at 2 in increments of 1
print(c)

[2 3 4 5 6 7]


Note this ends on 7, not 8 (does not include the top end of the interval).

In [ ]:
c = np.arange(10,50,5)   # Create an array of values starting at 10 in increments of 5
print(c)

[10 15 20 25 30 35 40 45]


Note this ends on 45, not 50 (does not include the top end of the interval).

In [ ]:
d = np.linspace(0, 4, num=5)
print(d)

[0. 1. 2. 3. 4.]
