# Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(0, 9, (3, 3))
print(a, end='\n\n')

bool_idx = a > 4  # Find the elements of a that are bigger than 2;
                  # this returns a numpy array of Booleans of the same
                  # shape as a, where each slot of bool_idx tells
                  # whether that element of a is > 2.

print(bool_idx)

[[1 5 3]
 [6 7 0]
 [1 2 5]]

[[False  True False]
 [ True  True False]
 [False False  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 3])

a[bool_idx] = 0
print(a)

[5 6 7 5]
[5 6 7 5]
[[1 0 3]
 [0 0 0]
 [1 2 0]]
