## numpy ndarray
An `ndarray` (short for "n-dimensional array") is the core data structure provided by the NumPy library in Python. It is a multi-dimensional, homogeneous array that can hold elements of the same data type. An ndarray can have one or more dimensions (**rank**), allowing you to represent a wide range of data, from simple one-dimensional lists to complex multi-dimensional matrices (tensors).

Key characteristics of ndarrays include:

1. **Homogeneous Data:** All elements within an ndarray must be of the same data type.

2. **Multi-dimensional:** Ndarrays can have any number of dimensions. For example, a 1D array is like a list and a 2D array is similar to a matrix.

3. **Indexed Access:** Elements within ndarrays are accessed using indexing, similar to Python lists. However, in ndarrays, you can use multi-dimensional indices to access elements in higher-dimensional arrays.

4. **Vectorized Operations:** Ndarrays enable vectorized operations, meaning that operations are automatically applied element-wise across the entire array without explicit loops.

Ndarrays are the foundation for most of NumPy's functionalities, including mathematical operations, linear algebra, statistical analysis, and more. They provide a powerful and efficient way to work with numerical data in Python.



# creating an ndarray array

NumPy provides several functions to create ndarrays with different shapes, data types, and initialization values. Here are some common options to create ndarrays:

1. creates an ndarray from a Python list.
1. creates an ndarray filled with zeros, ones.
1. creates an ndarray represent [arithmetic progression(AP)](https://he.wikipedia.org/wiki/%D7%A1%D7%93%D7%A8%D7%94_%D7%97%D7%A9%D7%91%D7%95%D7%A0%D7%99%D7%AA)(סדרה חשבונית). מופיע במחברת אחרת
1. creates an ndarray filled with randoum numbers.

In [ ]:
import numpy as np

### creates an ndarray from a Python list:

We can create a `ndaaray` by passing a Python list to `np.array()`.

![](https://drive.google.com/uc?export=view&id=1FnzwWIk3Ji-q8A6He3yfwnfkdfufz02o)

In [ ]:
a = np.array([1.3, 4, 2])  # Create a 1 dim ndaaray by a list
print(a, end='\n\n')

b = np.array([[3, 7, 1],
              [7, 5, 2]])  # Create a 2 dim ndaaray by a nested list
print(b, end='\n\n')

c = np.array([[1, 4, 2]])  # Create a 2 dim ndaaray by a nested list
print(c)

[1. 4. 2.]

[[3 7 1]
 [7 5 2]]

[[1 4 2]]


* The access to the array elements is by [i].
* The shape of the array can be checked by the `.shape` attribute
* The number of dimension of the array can be checked by the `.ndim` attribute.

In [ ]:
# 1-dimensional array
print(f'`a` first element is {a[0]}')
print(f'`a` second element is {a[1]}')
print(f'`a` third element is {a[2]}')

print(f'`a` shape is {a.shape}')
print(f'`a` shape is {a.ndim}')

print(a, ': before the change')
a[0] = 9  # Change first element of the array `a`
print(a, ': after the change')

`a` first element is 1.3
`a` second element is 4.0
`a` third element is 2.0
`a` shape is (3,)
`a` shape is 1
[1.3 4.  2. ] : before the change
[9. 4. 2.] : after the change


In [ ]:
# 2-dimensional array
print(f'`b` first row, first column is {b[0, 0]}')
print(f'`b` second row, second column is {b[1, 1]}')
print(f'`b` first row, third column is {b[0, 2]}')

print(f'`b` shape is {b.shape}')
print(f'`b` shape is {b.ndim}')

print('\n`b` before the changes:')
print(b)
b[0, 0] = 9  # Change first row, first column of the array `b`
b[1] = 9  # Change the entire second row the array `b`
print('\n`b` after the changes:')
print(b)

`b` first row, first column is 3
`b` second row, second column is 5
`b` first row, third column is 1
`b` shape is (2, 3)
`b` shape is 2

`b` before the changes:
[[3 7 1]
 [7 5 2]]

`b` after the changes:
[[9 7 1]
 [9 9 9]]


In [ ]:
# 2-dimensional array
print(f'`c` first row, first column is {c[0, 0]}')
print(f'`c` first row, second column is {c[0, 1]}')
print(f'`c` first row, third column is {c[0, 2]}')

print(f'`c` shape is {c.shape}')
print(f'`c` shape is {c.ndim}')

print('\n`c` before the changes:')
print(c)
c[0, 0] = 9  # Change first row, first column of the array `c`
print('\n`c` after the changes:')
print(c)

`c` first row, first column is 1
`c` first row, second column is 4
`c` first row, third column is 2
`c` shape is (1, 3)
`c` shape is 2

`c` before the changes:
[[1 4 2]]

`c` after the changes:
[[9 4 2]]


### creates an ndarray filled with zeros, ones:

![](https://drive.google.com/uc?export=view&id=1zoOyIUye_v1437vqgIgavOW1cfiY87iZ)

In [ ]:
a1 = np.ones(3)  # Create a 1 dim ndaaray
print(f'`a1` is:\n')
print(a1)
print(f'\n`a1` shape is {a1.shape}')
print(f'`a1` number of dimensions is {a1.ndim}\n\n')

a2 = np.ones((2, 3))  # Create a 2 dim ndaaray
print(f'`a2` is:\n')
print(a2)
print(f'\n`a2` shape is {a2.shape}')
print(f'`a2` number of dimensions is {a2.ndim}\n\n')

`a1` is:

[1. 1. 1.]

`a1` shape is (3,)
`a1` number of dimensions is 1


`a2` is:

[[1. 1. 1.]
 [1. 1. 1.]]

`a2` shape is (2, 3)
`a2` number of dimensions is 2




In [ ]:
b1 = np.zeros(3)  # Create a 1 dim ndaaray
print(f'`b1` is:\n')
print(b1)
print(f'\n`b1` shape is {b1.shape}')
print(f'`b1` number of dimensions is {b1.ndim}\n\n')

b2 = np.zeros((2, 3))  # Create a 2 dim ndaaray
print(f'`b2` is:\n')
print(b2)
print(f'\n`b2` shape is {b2.shape}')
print(f'`b2` number of dimensions is {b2.ndim}\n\n')

`b1` is:

[0. 0. 0.]

`b1` shape is (3,)
`b1` number of dimensions is 1


`b2` is:

[[0. 0. 0.]
 [0. 0. 0.]]

`b2` shape is (2, 3)
`b2` number of dimensions is 2




### creates an ndarray filled with randoum numbers

`np.random`: NumPy's random module provides various functions to create ndarrays with random values. For example:

* [`np.random.random`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) and [`np.random.rand`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html) that creates an ndarray filled with random values between 0 and 1


* [`np.random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

* [`np.random.randn`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [ ]:
# np.random.random Random values between 0 and 1
e1 = np.random.random(3)  # Create a 1 dim ndaaray
print(f'`e1` is:\n')
print(e1)
print(f'\n`e1` shape is {e1.shape}')
print(f'`e1` number of dimensions is {e1.ndim}\n\n')

e2 = np.random.random((2, 3))  # Create a 2 dim ndaaray
print(f'`e2` is:\n')
print(e2)
print(f'\n`e2` shape is {e2.shape}')
print(f'`e2` number of dimensions is {e2.ndim}\n\n')

`e1` is:

[7 5 4]

`e1` shape is (3,)
`e1` number of dimensions is 1


`e2` is:

[[0.40733306 0.10310354 0.1577361 ]
 [0.95038288 0.51993144 0.68013277]]

`e2` shape is (2, 3)
`e2` number of dimensions is 2


