# Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1.0, 2.0], dtype='int')  # Force a particular datatype

print('x:', x.dtype, 'y:', y.dtype, 'z:', z.dtype, end='\n\n')

print(x, y, z, sep='\n\n')

x: int64 y: float64 z: int64

[1 2]

[1. 2.]

[1 2]


In [ ]:
x = np.zeros(3)  # Let numpy choose the datatype
y = np.zeros(3, dtype='int')  # Force a particular datatype

print('x:', x.dtype, 'y:', y.dtype, end='\n\n')

print(x, y, sep='\n\n')

x: float64 y: int64

[0. 0. 0.]

[0 0 0]


In [ ]:
f1 = np.arange(10,50,5)  # Let numpy choose the datatype
f2 = np.arange(10,50,5, dtype='float')  # Force a particular datatype

print(f1)
print(f2)

[10 15 20 25 30 35 40 45]
[10. 15. 20. 25. 30. 35. 40. 45.]
