In [2]:
import numpy as np

lin_array = np.linspace(0,1,num=11)
print(lin_array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [6]:
import numpy as np

x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [7]:
np.ones(2)

array([1., 1.])

In [10]:
mat1 = np.random.randint(0, 9, 3*3)
print(mat1)

[3 6 7 2 8 7 6 0 4]


In [ ]:
import numpy as np

arr = np.array([-1, 2, -3, 4, -5])
arr_mod = np.where(arr < 0, 0, arr)

print(arr_mod)

[0 2 0 4 0]


In [14]:
import numpy as np

arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
import numpy as np

# Generate a linearly spaced array between 10 and 20 with 11 points
lin_array = np.linspace(10, 20, num=11)

# Print the resulting array
print(lin_array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [16]:
import numpy as np

arr = np.array([1, 2, 3])
diag_matrix = np.diag(arr)
print(diag_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
